export const ErrorCodes = {
  CONFLICT_EMAIL: "CONFLICT_EMAIL",
  CONFLICT_TAG_DUPLICATE: "CONFLICT_TAG_DUPLICATE",
  NOT_FOUND_USER: "NOT_FOUND_USER",
  NOT_FOUND_URL: "NOT_FOUND_URL",
  NOT_FOUND_TAG: "NOT_FOUND_TAG",
  GONE_EXPIRED: "GONE_EXPIRED",
};
